version: 2
updates:
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    groups:
      web:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /tests
    schedule:
      interval: weekly
    groups:
      e2e:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
    groups:
      backend:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /simulator
    schedule:
      interval: weekly
    groups:
      simulator:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
