query GetPropertyDefinitions($rootLocationIds: [ID!]) {
  propertyDefinitions(rootLocationIds: $rootLocationIds) {
    id
    name
    description
    fieldType
    isActive
    allowedEntities
    options
    visibility
    ownerUserId
    canEdit
    locationId
    location {
      id
      title
      kind
      parent {
        id
        title
        kind
        parent {
          id
          title
          kind
        }
      }
    }
  }
}

query GetPropertiesForSubject($subjectId: ID!, $subjectType: PropertyEntity!, $rootLocationIds: [ID!]) {
  propertyDefinitions(rootLocationIds: $rootLocationIds) {
    id
    name
    description
    fieldType
    isActive
    allowedEntities
    options
    visibility
    ownerUserId
    canEdit
    locationId
    location {
      id
      title
      kind
      parent {
        id
        title
        kind
        parent {
          id
          title
          kind
        }
      }
    }
  }
}

