mutation CreatePropertyDefinition($data: CreatePropertyDefinitionInput!) {
  createPropertyDefinition(data: $data) {
    id
    name
    description
    fieldType
    isActive
    allowedEntities
    options
    visibility
    ownerUserId
    canEdit
    locationId
    location {
      id
      title
      kind
      parent {
        id
        title
        kind
        parent {
          id
          title
          kind
        }
      }
    }
  }
}

mutation UpdatePropertyDefinition($id: ID!, $data: UpdatePropertyDefinitionInput!) {
  updatePropertyDefinition(id: $id, data: $data) {
    id
    name
    description
    fieldType
    isActive
    allowedEntities
    options
    visibility
    ownerUserId
    canEdit
    locationId
    location {
      id
      title
      kind
      parent {
        id
        title
        kind
        parent {
          id
          title
          kind
        }
      }
    }
  }
}

mutation DeletePropertyDefinition($id: ID!) {
  deletePropertyDefinition(id: $id)
}

