query TaskPresets($rootLocationIds: [ID!]) {
  taskPresets(rootLocationIds: $rootLocationIds) {
    id
    name
    key
    visibility
    ownerUserId
    isOwner
    locationId
    location {
      id
      title
      kind
      parent {
        id
        title
        kind
        parent {
          id
          title
          kind
        }
      }
    }
    graph {
      nodes {
        id
        title
        description
        priority
        estimatedTime
      }
      edges {
        fromId
        toId
      }
    }
  }
}

query TaskPreset($id: ID!) {
  taskPreset(id: $id) {
    id
    name
    key
    visibility
    ownerUserId
    isOwner
    locationId
    location {
      id
      title
      kind
      parent {
        id
        title
        kind
        parent {
          id
          title
          kind
        }
      }
    }
    graph {
      nodes {
        id
        title
        description
        priority
        estimatedTime
      }
      edges {
        fromId
        toId
      }
    }
  }
}
