mutation CreateTaskPreset($data: CreateTaskPresetInput!) {
  createTaskPreset(data: $data) {
    id
    name
    key
    visibility
    ownerUserId
    isOwner
    locationId
    location {
      id
      title
      kind
      parent {
        id
        title
        kind
        parent {
          id
          title
          kind
        }
      }
    }
    graph {
      nodes {
        id
        title
        description
        priority
        estimatedTime
      }
      edges {
        fromId
        toId
      }
    }
  }
}

mutation UpdateTaskPreset($id: ID!, $data: UpdateTaskPresetInput!) {
  updateTaskPreset(id: $id, data: $data) {
    id
    name
    key
    visibility
    ownerUserId
    isOwner
    locationId
    location {
      id
      title
      kind
      parent {
        id
        title
        kind
        parent {
          id
          title
          kind
        }
      }
    }
    graph {
      nodes {
        id
        title
        description
        priority
        estimatedTime
      }
      edges {
        fromId
        toId
      }
    }
  }
}

mutation DeleteTaskPreset($id: ID!) {
  deleteTaskPreset(id: $id)
}
