"""empty message

Revision ID: ac24ef41bd41
Revises: 
Create Date: 2025-12-12 19:00:58.216109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac24ef41bd41'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['location_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('field_type', sa.String(), nullable=False),
    sa.Column('options', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allowed_entities', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('firstname', sa.String(), nullable=False),
    sa.Column('lastname', sa.String(), nullable=False),
    sa.Column('birthdate', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('assigned_location_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_location_id'], ['location_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('assignee_id', sa.String(), nullable=True),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('definition_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('text_value', sa.String(), nullable=True),
    sa.Column('number_value', sa.Float(), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('date_value', sa.Date(), nullable=True),
    sa.Column('date_time_value', sa.DateTime(), nullable=True),
    sa.Column('select_value', sa.String(), nullable=True),
    sa.Column('multi_select_values', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['property_definitions.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_dependencies',
    sa.Column('previous_task_id', sa.String(), nullable=False),
    sa.Column('next_task_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['next_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['previous_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('previous_task_id', 'next_task_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    op.drop_table('property_values')
    op.drop_table('tasks')
    op.drop_table('patients')
    op.drop_table('users')
    op.drop_table('property_definitions')
    op.drop_table('location_nodes')
    # ### end Alembic commands ###
